baseURL = "https://cuddleseattle.com/"
languageCode = "en-US"
title = "Happy Humanimals"
theme = "congo"
enableRobotsTXT = true

[params]
  colorScheme = "purple"
  defaultAppearance = "light"
  autoSwitchAppearance = false
  description = "Platonic touch and consent workshops in Seattle. Cuddles & Connection events for curious, hopeful, and nervous newcomers."
  mainSections = []
  eventbriteUrl = "https://www.eventbrite.com/o/69485758173"
  canonicalURL = true

[params.homepage]
  layout = "custom"
  showRecent = false

[params.header]
  layout = "basic"

[params.footer]
  showCopyright = true
  showThemeAttribution = false

[params.article]
  showDate = false
  showAuthor = false
  showReadingTime = false
  showTableOfContents = false

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menus.main]]
    name = "Learn More"
    pageRef = "/learn-more"
    weight = 2

  [[menus.footer]]
    name = "Eventbrite"
    url = "https://www.eventbrite.com/o/69485758173?utm_source=cuddleseattle&utm_medium=website&utm_content=footer"
    weight = 1
  [[menus.footer]]
    name = "Newsletter"
    url = "https://happyhumanimals.substack.com"
    weight = 2
